name: masa_epico_concrete_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  collection: ^1.18.0
  data_table_2: ^2.5.15
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.6
  injector: ^3.0.0
  intl: ^0.19.0
  path: ^1.8.3
  pdf: ^3.11.0
  quickalert: ^1.1.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:    
  - family: Heebo
    fonts:
      - asset: fonts/Heebo-Regular.ttf
  assets: 
    - images/masa-control.png
    - dev.env
    - init.sql
